Alter table Aircrafts add Constraint AcID_pk primary key(AcID);
Alter table Route add Constraint RtID_pk primary key(RtID);
Alter table Route add Constraint RouteCode_uk unique(RouteCode);
Alter table AirFare add Constraint AfID_pk primary key(AfID);
Alter table AirFare add Constraint fk_Route foreign key(Route) references Route(RtID) ;
Alter table Flight_Schedule add Constraint FlID_pk primary key(FlID);
Alter table Flight_Schedule add Constraint fk_Aircraft foreign key(AirCraft) references AirCrafts(AcID);
Alter table Flight_Schedule add Constraint fk_NetFare foreign key(NetFare) references AirFare(AfID);
Alter table Discounts add Constraint DiID_pk primary key(DiID);
Alter table Charges add Constraint ChID_pk primary key(ChID);
Alter table Countries add Constraint CtID_pk primary key(CtID);
Alter table States add Constraint StID_pk primary key(StID);
Alter table States add Constraint fk_CountryOfPassenger foreign key(Country) references Countries(CtID);
Alter table Passengers add Constraint PsID_pk primary key(PsID);
Alter table Passengers add Constraint fk_StateOfPassenger foreign key(State) references States(StID);
Alter table Branches add Constraint BrID_PK primary key(BrID);
Alter table Branches add Constraint fk_StateOfEmployeee foreign key(State) references States(StID);
Alter table Employees add Constraint EmpID_ID primary key(EmpID);
Alter table Employees add Constraint fk_Branch foreign key(Branch) references Branches(BrID);
Alter table Transactions add Constraint TsID_ID primary key(TsID);
Alter table Transactions add Constraint fk_Passenger foreign key(Passenger) references Passengers(PsID);
Alter table Transactions add Constraint fk_Flight foreign key(Flight) references Flight_Schedule(FlID);
Alter table Transactions add Constraint fk_Employee foreign key(Employee) references Employees(EmpID);
Alter table Transactions add Constraint fk_Charges foreign key(Charges) references Charges(ChID);
Alter table Transactions add Constraint fk_Discount foreign key(Discount) references Discounts(DiID);