drop table Transactions;
drop table Employees;
drop table Passengers;
drop table Flight_Schedule;
drop table Aircrafts;
drop table AirFare;
drop table Route;
drop table Discounts;
drop table Charges;
drop table Branches;
drop table states;
drop table Countries;
create table Aircrafts (AcID int,AcNumber varchar(32) not null,Capacity int not null,MfdBy varchar(128) not null,MfdOn date not null);
create table Route (RtID int,Airport varchar(32) not null,Destination varchar(32) not null,RouteCode varchar(16) not null);
create table AirFare (AfID INT,Route int,Fare number,FSC number);
create table Flight_Schedule (FlID int,FlightDate date not null,Departure date,Arrival date,AirCraft int,NetFare int);
create table Discounts (DiID int,Title varchar(32),Amount int,Description varchar(255));
create table Charges (ChID int,Title varchar(32),Amount int,Description varchar(255));
create table Countries (CtID int,CountryName varchar(32) not null);
create table states(StID int,StateName varchar(32),Country int);
create table Passengers (PsID int,Name varchar(32) not null,Address varchar(64) not null,Age int not null,Nationalities varchar(16) not null,Email varchar(32) not null,Cell varchar(16) not null,Tel Varchar(16),Street varchar(64),State int);
create table Branches (BrID int,Center varchar(16) not null,Address varchar(32) not null,State int);
create table Employees (EmpID int,Name varchar(32) not null,Address varchar(32) not null,Branch int not null,Designation varchar(32) not null,Email varchar(32) not null,Tel varchar(16) not null);
create table Transactions (TsID int,BookingDate date not null,DepartureDate date not null,Passenger int,Flight int,Type varchar(16),Employee  int,Charges int,Discount int,Total int not null);